@api = http://localhost:3020/atom
#@api = http://187.229.22.99:8010/api/v1/prod-serv
### GET
GET {{api}}/users
### GET ITEM

GET {{api}}/user/yvfeacostaca@ittepic.edu.mx
GET {{api}}/user/rotopetear@ittepic.edu.mx

POST {{api}}/login
Content-Type: application/json

{
    "correo": "yvfeacostaca@ittepic.edu.mx",
    "contrasena":"123456777"
}


##POST nuevo USUARIO /register
POST {{api}}/register
Content-Type: application/json

{
    "nombre": "Yvan Fernando",
    "apellidos": "Acosta Carrillo",
    "correo": "yvfeacostaca@ittepic.edu.mx",
    "contrasena":"123456",
    "edad": 22,
    "ocupacion":"Estudiante",
    "objetivos_user": [],
    "detail_row":{
        "Activo": true,
        "Borrado": false,
        "detail_row_reg":[
            {
                "FechaReg": "2025-02-27",
                "UsuarioReg":"yvfeacostaca",
                "FechaUltMod": "2025-02-27",
                "UsuarioMod":"yvfeacostaca"
            }
        ]
    }
}

##cambiar contraseña SE CAMBIA EL TOKEN ANTES DE PROBAR PARA ESTE PEDO
PUT {{api}}/cambiar-contrasena
Content-Type: application/json
Authorization: Bearer 

{
    "oldPass":"123456",
    "newPass":"1234567"
}

##Cambiar datos de la cuenta
PUT {{api}}/cambiar-nomap
Content-Type: application/json

{
    "correo": "yvfeacostaca@ittepic.edu.mx",
    "nombre":"Yvan Fernando",
    "apellidos":"Acosta Carrillo"
}

PUT {{api}}/cambiar-nomus
Content-Type: application/json

{
    "correo": "yvfeacostaca@ittepic.edu.mx",
    "nombreUsuario":"ElGatoMaster344"
}

PUT {{api}}/cambiar-ocupacion
Content-Type: application/json

{
    "correo": "yvfeacostaca@ittepic.edu.mx",
    "ocupacion":"Emprendedor"
}

##-------------------EVENTOS --Cambiar el token QUE SE DA AL INICIAR SESION
POST {{api}}/event/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQyNDQyNzI5LCJleHAiOjE3NDI0NTM1Mjl9.nH6VrOS0F80FFeg6hA-6FxUYrx2AxcWuZV3L_TGVO_4

{
    "titulo": "TOÑO",
    "descripcion": "BALATREAR",
    "fechaInicio": "2025-03-28",
    "fechaFin": "2025-03-29",
    "recordatorio": false,
    "repeticion": false
}

##Lista de eventos CAMBIAR EL TOKEN
GET {{api}}/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQyNDQyNzI5LCJleHAiOjE3NDI0NTM1Mjl9.nH6VrOS0F80FFeg6hA-6FxUYrx2AxcWuZV3L_TGVO_4


# GET {{api}}/events-proximos
# Content-Type: application/json

# {
#     "correo": "yvfeacostaca@ittepic.edu.mx"
# }

# GET {{api}}/events-vencidos
# Content-Type: application/json

# {
#     "correo": "yvfeacostaca@ittepic.edu.mx"
# }


##Evento en especifico
GET {{api}}/event/yvf-1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQyNDQyNzI5LCJleHAiOjE3NDI0NTM1Mjl9.nH6VrOS0F80FFeg6hA-6FxUYrx2AxcWuZV3L_TGVO_4




##Actualizar evento
PUT {{api}}/event-update/yvf-1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQyNDQyNzI5LCJleHAiOjE3NDI0NTM1Mjl9.nH6VrOS0F80FFeg6hA-6FxUYrx2AxcWuZV3L_TGVO_4

{
    "correo": "yvfeacostaca@ittepic.edu.mx",
    "titulo": "Vistar a mi abuela",
    "descripcion": "Ir al panteon para estar un rato con mi abuela",
    "fechaInicio": "2025-03-06",
    "fechaFin": "2025-03-06",
    "recordatorio": false,
    "repeticion": false
}




##Eliminar evento
DELETE {{api}}/event-delete/yvf-2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQyNDQyNzI5LCJleHAiOjE3NDI0NTM1Mjl9.nH6VrOS0F80FFeg6hA-6FxUYrx2AxcWuZV3L_TGVO_4

{
    "correo": "yvfeacostaca@ittepic.edu.mx"
}


### Create a new task
POST {{api}}/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQ4NzEwMTk0LCJleHAiOjE3NDg3MjA5OTR9.GxocAfhxt2zxwWvBdbMw-QIeo-iFYZm879WM4lpRUso

{
    "titulo": "Tarea 1",
    "descripcion": "FRANCO ESCAMILLA",
    "fechaLimite": "2026-03-30T00:00:00",
    "completada": false
    
}


## TAREAS-
GET {{api}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQ4MTIxNjM4LCJleHAiOjE3NDgxMzI0Mzh9.dDWL3lho6EN32Kha3Yfm5Hp-hosjjydO0mfhuK0tru0

DELETE {{api}}/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJZdmFuIEZlcm5hbmRvIiwiY29ycmVvIjoieXZmZWFjb3N0YWNhQGl0dGVwaWMuZWR1Lm14IiwiaWF0IjoxNzQ4ODA5MzQxLCJleHAiOjE3NDg4MjAxNDF9.8QT666eZ9d5SVH5gxidJkjmWfUjaF49U6cAI4-RH3K4